apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
- name: redirectd-placeholder
  newName: 975049915785.dkr.ecr.ap-southeast-1.amazonaws.com/gogov-redirectd
