apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: govtech-elasticsearch
  namespace: elasticsearch
spec:
  version: 8.17.0
  http:
    tls:
      selfSignedCertificate:
        disabled: true # Disable https
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp3-elasticsearch
