apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-gogov-elasticsearch-es-default-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-elasticsearch
  resources:
    requests:
      storage: 1Gi
