apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: gogov
spec:
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: gogov-elasticsearch
  ports:
    - name: https
      port: 9200
      targetPort: 9200
      protocol: TCP
