apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: gogov
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: quay.io/strimzi/kafka:0.44.0-kafka-3.8.0
          env:
            - name: LOG_DIR
              value: "/tmp/logs"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
              name: zookeeper-client
          command: ["sh", "-c"]
          args:
            - >
              bin/zookeeper-server-start.sh config/zookeeper.properties
