apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: gogov
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
  #     name: zookeeper-client
  # selector:
  #   app: zookeeper
  # type: ClusterIP
