# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: analytics-aggregator
# spec:
#   template:
#     spec:
#       containers:
#         - name: analytics-aggregator
#           env:
#             - name: KAFKA_ADDR
#               valueFrom:
#                 secretKeyRef:
#                   name: anal-secret
#                   key: KAFKA_ADDR
#             - name: ELASTIC_URL
#               valueFrom:
#                 secretKeyRef:
#                   name: anal-secret
#                   key: ELASTIC_URL
#             - name: ELASTIC_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: anal-secret
#                   key: ELASTIC_USER
#             - name: ELASTIC_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: anal-secret
#                   key: ELASTIC_PASSWORD
