apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-aggregator
  labels:
    app: analytics-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-aggregator
  template:
    metadata:
      labels:
        app: analytics-aggregator
    spec:
      containers:
        - name: analytics-aggregator
          image: analytics-aggregator-placeholder
