# This is meant for local development only. Do not use this in production.
version: "3.8"
services:
  ps-postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: gogov-local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ps-postgres:/var/lib/postgresql/data
volumes:
  ps-postgres:
