# Use the base image from the root Dockerfile
FROM node:20.11.1

# Set the working directory
WORKDIR /usr/src/app

# Copy specific sub-application files
COPY apps/web/package.json apps/web/pnpm-lock.yaml ./
COPY apps/web ./

# Install dependencies and build the web application
RUN pnpm install
RUN pnpm run build

# Expose the port for the web application
EXPOSE 8888

# Command to run the web application
CMD ["pnpm", "start"]
