apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prometheus-placeholder
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--log.level=debug"
          ports:
            - containerPort: 9090
            - containerPort: 9464
