---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: prom-ui
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: prom-exporter
      protocol: TCP
      port: 9464
      targetPort: 9464