version: "3.8"

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - ps-postgres
      - redis

  ps-postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRESDB}
      - POSTGRES_USER=${POSTGRESUSER}
      - POSTGRES_PASSWORD=${POSTGRESPASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ps-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - 6379:6379

volumes:
  ps-postgres:
