FROM node:20 AS base

FROM base AS builder

RUN npm i -g pnpm@9.1.3
RUN npm i -g turbo@^1.12.5
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PATH:$PNPM_HOME

WORKDIR /app

COPY . .

RUN ["pnpm", "turbo", "prune", "web"]

WORKDIR /app/out

RUN pnpm install

WORKDIR /app/out/apps/web
RUN npx prisma generate

CMD ["npx", "tsx", "./kafka-consumer/index.ts"]