FROM node:20 AS base

FROM base AS builder

RUN npm i -g pnpm@9.1.3
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PATH:$PNPM_HOME

WORKDIR /app

COPY . .

RUN pnpm install

WORKDIR /app/apps/web
RUN npx prisma generate
RUN pnpm build-outbox

FROM base AS runner
WORKDIR /gogov-outbox

COPY --from=builder /app/apps/web/dist/outbox ./

CMD ["node", "--include-source-maps","index.js"]