apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      initContainers:
        - name: migrate-database
          image: web
          command: ["sh", "-c", "echo 'Hello, World from InitContainer!' && sleep 5"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_URL
            - name: DIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DIRECT_URL
      containers:
        - name: web
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: NODE_ENV
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: REDIS_URL
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: REDIS_PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_URL
            - name: DIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DIRECT_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: NEXTAUTH_SECRET
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: NEXTAUTH_URL
            - name: AWS_REGION
              value: 'ap-southeast-1'
            - name: SES_EMAIL_SOURCE
              value: 'gogov@sandbox.tech.gov.my'
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: STORAGE_BASE_URL
              value: 'https://gogov-web-staging.s3.ap-southeast-1.amazonaws.com'
            - name: STORAGE_BUCKET_NAME
              value: 'gogov-web-staging'
            - name: REDIRECT_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: REDIRECT_SERVER_URL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: API_KEY
            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: API_SECRET_KEY
            - name: ENCRYPTION_KEY_ID
              value: 'alias/gogov-dev'
            - name: NEXT_PUBLIC_APP_ENV
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: NEXT_PUBLIC_APP_ENV
            - name: STAGING_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: STAGING_AUTH_PASSWORD
