apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: NEXT_PUBLIC_APP_NAME
              value: GoGovMy
            - name: NEXT_PUBLIC_APP_DOMAIN
              value: app.pautan.org
            - name: NEXT_PUBLIC_APP_SHORT_DOMAIN
              value: pautan.org
            - name: NODE_ENV
              value: development
            - name: REDIS_URL
              value: redis://localhost:6379
            - name: REDIS_PORT
              value: "6379"
            - name: DATABASE_URL
              value: postgresql://gnuadmin:um1:YzbwIWUL3o<dU2F$!h#yWgqi@gogov-go-tmp.c1gawegee1ay.ap-southeast-1.rds.amazonaws.com:5432/GoGovDev?schema=public
            - name: DIRECT_URL
              value: postgresql://gnuadmin:um1:YzbwIWUL3o<dU2F$!h#yWgqi@gogov-go-tmp.c1gawegee1ay.ap-southeast-1.rds.amazonaws.com:5432/GoGovDev?schema=public
            - name: NEXTAUTH_SECRET
              value: f5ae034320dd210e3800e38272ee6ab5
            - name: NEXTAUTH_URL
              value: https://app.pautan.org
            - name: AWS_ACCESS_KEY_ID
              value: AKIA465AS263KVIT7QDK
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: AWS_REGION
              value: ap-southeast-2
            - name: SES_EMAIL_SOURCE
              value: no-reply@web3ramen.com
            - name: GOOGLE_CLIENT_ID
              value: 34998620114-rah2h9r09ugdiinm5ehaekc8ijleu6ag.apps.googleusercontent.com
            - name: GOOGLE_CLIENT_SECRET
              value: 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
            - name: STORAGE_ACCESS_KEY_ID
              value: AKIA465AS263KVIT7QDK
            - name: STORAGE_SECRET_ACCESS_KEY
              value: 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
            - name: STORAGE_ENDPOINT
              value: https://gogovmy-dev.s3.ap-southeast-2.amazonaws.com/
            - name: STORAGE_BASE_URL
              value: https://gogovmy-dev.s3.ap-southeast-2.amazonaws.com/
            - name: REDIRECT_SERVER_URL
              value: http://localhost:3000
        - name: web-outbox
          env:
            - name: ANALYTIC_TOPIC
              value: link_analytics
            - name: OUTBOX_TOPIC
              value: ps-postgres.public.WebhookOutbox
            - name: KAFKA_BROKER_URL
              value: b-2.gogovdev.eshbn0.c5.kafka.ap-southeast-1.amazonaws.com:9092
