apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: NEXT_PUBLIC_APP_NAME
              value: "GoGovMy"
            - name: NEXT_PUBLIC_APP_DOMAIN
              value: "app.pautan.org"
            - name: NEXT_PUBLIC_APP_SHORT_DOMAIN
              value: "pautan.org"
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: NODE_ENV
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: REDIS_URL
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: REDIS_PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_URL
            - name: DIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DIRECT_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: NEXTAUTH_SECRET
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: NEXTAUTH_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: AWS_REGION
            - name: SES_EMAIL_SOURCE
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: SES_EMAIL_SOURCE   
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: GOOGLE_CLIENT_ID
            - name: STORAGE_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: STORAGE_ACCESS_KEY_ID
            - name: STORAGE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: STORAGE_SECRET_ACCESS_KEY
            - name: STORAGE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: STORAGE_ENDPOINT
            - name: STORAGE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: STORAGE_BASE_URL
            - name: REDIRECT_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: REDIRECT_SERVER_URL
