apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogov-landing
spec:
  template:
    spec:
      containers:
        - name: gogov-landing
          env:
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: APP_ENV
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: AUTH_TOKEN
            - name: LANDING_STATS_JSON_URL
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: LANDING_STATS_JSON_URL
