apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
spec:
  template:
    spec:
      containers:
        - name: landing-page
          env:
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: "production"
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: "admin"
            - name: LANDING_STATS_JSON_URL
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: "https://gogov-web-staging.s3.ap-southeast-1.amazonaws.com/public/stats.json"
