apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana-placeholder
          ports:
            - containerPort: 3004
          volumeMounts:
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources/datasources.yml
            subPath: datasources.yml
          - name: grafana-dashboards
            mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
            subPath: dashboards.yml
          - name: grafana-dashboard-files
            mountPath: /var/lib/grafana/dashboards
          - name: request_status_code
            mountPath: /var/lib/grafana/dashboards/request_status_code.json
            subPath: request_status_code.json
          - name: average_request_time
            mountPath: /var/lib/grafana/dashboards/average_request_time.json
            subPath: average_request_time.json
        volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources-config
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards-config
        - name: grafana-dashboard-files
          configMap:
            name: grafana-dashboard-files-config
