apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogov-kafka
  namespace: gogov
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: quay.io/strimzi/kafka:0.44.0-kafka-3.8.0
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:29092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: LOG_DIR
              value: "/tmp/logs"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          ports:
            - containerPort: 9092
              name: kafka-broker
            - containerPort: 29092
              name: kafka-internal
          readinessProbe:
            exec:
              command:
                - "/opt/kafka/bin/kafka-topics.sh"
                - "--bootstrap-server"
                - "localhost:9092"
                - "--list"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - "/opt/kafka/bin/kafka-topics.sh"
                - "--bootstrap-server"
                - "localhost:9092"
                - "--list"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          command: ["sh", "-c"]
          args:
            - >
              bin/kafka-server-start.sh config/server.properties
              --override listeners=${KAFKA_LISTENERS}
              --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS}
              --override zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}
              --override inter.broker.listener.name=${KAFKA_INTER_BROKER_LISTENER_NAME}
              --override listener.security.protocol.map=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
