apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-internal
      protocol: TCP
      port: 29092
      targetPort: 29092
    - name: kafka-external
      protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP
