apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
    - name: broker-internal
      protocol: TCP
      port: 29092
      targetPort: 29092
    - name: broker-external
      protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP
