FROM node:20.5-alpine AS base

RUN apk update && apk upgrade

WORKDIR /app

COPY package*.json ./

#install pnpm first
RUN ["npm", "install", "-g", "pnpm@9.1.3"]

#install turbo first
RUN ["npm", "install", "-g", "turbo@^1.12.5"]

RUN ["npm", "i"]

COPY . .

RUN npm run generate

FROM nginx:alpine

COPY --from=base /app/out /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]