FROM node:20.5-alpine AS base

RUN apk update && apk upgrade

WORKDIR /app

COPY package*.json ./

RUN NODE_ENV=development npm ci

COPY . .

RUN npm run generate

FROM nginx:alpine

COPY --from=base /app/out /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]