apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogov-landing-app
spec:
  template:
    spec:
      containers:
        - name: gogov-landing-app
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: NEXT_PUBLIC_API_BASE_URL
            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: API_SECRET_KEY
            - name: NEXT_PUBLIC_APP_URL
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: NEXT_PUBLIC_APP_URL
            - name: LANDING_STATS_JSON_URL
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: LANDING_STATS_JSON_URL
            - name: ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: ALLOWED_ORIGINS
            - name: NEXT_PUBLIC_APP_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: NEXT_PUBLIC_APP_DOMAIN
            - name: NEXT_PUBLIC_LANDING_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: NEXT_PUBLIC_LANDING_DOMAIN
            - name: NEXT_PUBLIC_LAST_UPDATED
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: NEXT_PUBLIC_LAST_UPDATED
            - name: NEXT_PUBLIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: NEXT_PUBLIC_APP_NAME
            - name: NEXT_PUBLIC_APP_ENV
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: NEXT_PUBLIC_APP_ENV
            - name: STAGING_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: STAGING_AUTH_PASSWORD
