FROM node:20-alpine AS base

RUN apk update && apk upgrade

WORKDIR /app

#install pnpm first
RUN ["npm", "install", "-g", "pnpm@9.1.3"]

COPY cron.ts /app

ARG WEB_BASE

RUN ["pnpm", "i"]

CMD ["sh", "-c", "node cron.ts"]
