apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster
spec:
  template:
    spec:
      containers:
        - name: kafka
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '200m'
