apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: gogov-kafka-cluster
spec:
  kafka:
    resources:
      requests:
        memory: 256Mi
        cpu: '100m'
      limits:
        memory: 512Mi
        cpu: '200m'
  zookeeper:
    resources:
      requests:
        memory: 256Mi
        cpu: '100m'
      limits:
        memory: 512Mi
        cpu: '200m'
