apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: gogov
spec:
  template:
    spec:
      containers:
        - name: kafka-connect
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: 'kafka-cluster-kafka-brokers:9092'
            - name: CONNECT_GROUP_ID
              value: 'kafka-connect-staging'
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: 'connect-configs'
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: 'connect-offsets'
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: 'connect-status'
            - name: CONNECT_KEY_CONVERTER
              value: 'org.apache.kafka.connect.json.JsonConverter'
            - name: CONNECT_VALUE_CONVERTER
              value: 'org.apache.kafka.connect.json.JsonConverter'
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: 'kafka-connect.staging.internal'
            - name: CONNECT_REST_PORT
              value: '8083'
