apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: 767397910274.dkr.ecr.ap-southeast-1.amazonaws.com/gogov-kafka-connect
    newName: 767397910274.dkr.ecr.ap-southeast-1.amazonaws.com/gogov-kafka-connect
    newTag: latest
