apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirectd
  labels:
    app: redirectd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirectd
  template:
    metadata:
      labels:
        app: redirectd
    spec:
      containers:
      - name: redirectd
        image: redirectd
        ports:
        - containerPort: 3000
