apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-outbox
spec:
  template:
    spec:
      containers:
        - name: web-outbox
          env:
            - name: ANALYTIC_TOPIC
              value: "link_analytics"
            - name: OUTBOX_TOPIC
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: OUTBOX_TOPIC
            - name: KAFKA_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: KAFKA_BROKER_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_URL
            - name: DIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DIRECT_URL