apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-outbox
spec:
  template:
    spec:
      containers:
        - name: web-outbox
          env:
            - name: KAFKA_OUTBOX_TOPIC
              valueFrom:
                secretKeyRef:
                  name: web-outbox-secrets
                  key: KAFKA_OUTBOX_TOPIC
            - name: KAFKA_ANALYTIC_TOPIC
              valueFrom:
                secretKeyRef:
                  name: web-outbox-secrets
                  key: KAFKA_ANALYTIC_TOPIC
            - name: KAFKA_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: web-outbox-secrets
                  key: KAFKA_BROKER_URL
            - name: ENCRYPTION_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: web-outbox-secrets
                  key: ENCRYPTION_KEY_ID
            - name: KAFKA_GROUP_ID_REDIRECT
              valueFrom:
                secretKeyRef:
                  name: web-outbox-secrets
                  key: KAFKA_GROUP_ID_REDIRECT
            - name: KAFKA_GROUP_ID_ANALYTICS
              valueFrom:
                secretKeyRef:
                  name: web-outbox-secrets
                  key: KAFKA_GROUP_ID_ANALYTICS
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: web-outbox-secrets
                  key: DATABASE_URL
