apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web-outbox
          env:
            - name: ANALYTIC_TOPIC
              value: link_analytics
            - name: OUTBOX_TOPIC
              value: ps-postgres.public.WebhookOutbox
            - name: KAFKA_BROKER_URL
              value: b-2.gogovdev.eshbn0.c5.kafka.ap-southeast-1.amazonaws.com:9092
