apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-outbox
spec:
  template:
    spec:
      containers:
        - name: web-outbox
          env:
            - name: ANALYTIC_TOPIC
              value: "link_analytics"
            - name: OUTBOX_TOPIC
              value: "ps-postgres.public.WebhookOutbox"
            - name: KAFKA_BROKER_URL
              value: "b-2.gogovdevtmp.u9vhh4.c5.kafka.ap-southeast-1.amazonaws.com:9092"
            - name: DATABASE_URL
              value: "postgresql://gnuadmin:um1%3AYzbwIWUL3o%3CdU2F%24!h%23yWgqi@gogov-go-tmp.c1gawegee1ay.ap-southeast-1.rds.amazonaws.com:5432/GoGovDev?schema=public"
            - name: DIRECT_URL
              value: "postgresql://gnuadmin:um1%3AYzbwIWUL3o%3CdU2F%24!h%23yWgqi@gogov-go-tmp.c1gawegee1ay.ap-southeast-1.rds.amazonaws.com:5432/GoGovDev?schema=public"
