apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  template:
    spec:
      containers:
        - name: kafka-exporter
          env:
            - name: kafka.server
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: KAFKA_BROKER_URL