FROM node:20.5-alpine AS builder

RUN npm i -g pnpm@9.1.3
RUN npm i -g turbo@^1.12.5
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PATH:$PNPM_HOME

WORKDIR /app

COPY . .

WORKDIR /app/apps/redirect-pages/next-landing-page

ARG LANDING_STATS_JSON_URL

RUN npm install
RUN npm run build

FROM nginx:alpine

RUN apk add --no-cache nodejs npm

WORKDIR /app

COPY --from=builder /app/apps/redirect-pages/next-landing-page ./
COPY --from=builder /app/apps/redirect-pages/next-landing-page/.next ./.next
COPY --from=builder /app/apps/redirect-pages/next-landing-page/public ./public

COPY apps/redirect-pages/next-landing-page/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["sh", "-c", "nginx && npm run start"]
