FROM grafana/grafana@sha256:eff6b95b4d17c5a966ed72bc155685d9bc2e704c455ad7c246df6e786ed3289a

EXPOSE 3004

# Use environment variables instead of hardcoded values
ENV GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
ENV GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

# Provision data sources
COPY ./docker/grafana/datasources.yml /etc/grafana/provisioning/datasources/datasources.yml

# Provision dashboard
COPY ./docker/grafana/dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml

COPY ./docker/grafana/dashboards/request_status_code.json /var/lib/grafana/dashboards/request_status_code.json
COPY ./docker/grafana/dashboards/average_request_time.json /var/lib/grafana/dashboards/average_request_time.json
COPY ./docker/grafana/dashboards/kafka_offset.json /var/lib/grafana/dashboards/kafka_offset.json

RUN echo "Listing files in the current directory:" && ls -la

CMD [ \
    "grafana-server", \
    "--homepath=/usr/share/grafana", \
    "--config=/etc/grafana/grafana.ini", \
    "cfg:default.paths.logs=/var/log/grafana", \
    "cfg:default.paths.data=/var/lib/grafana", \
    "cfg:default.paths.plugins=/var/lib/grafana/plugins" \
    ]