FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY ../apps/redirect-server/go.mod ../apps/redirect-server/go.sum ./

RUN go mod download

COPY ../apps/redirect-server .

RUN go build -o analytics-aggregator ./cmd/analytics-aggregator

FROM alpine:latest

COPY --from=builder /app/analytics-aggregator /analytics-aggregator

CMD [ \
    "/analytics-aggregator" \
    ]
