FROM node:23.4.0-alpine AS base

RUN apk update && apk upgrade

WORKDIR /app

#install pnpm first
RUN [ \
    "npm", \
    "install", \
    "-g", \
    "pnpm@9.1.3" \
    ]

#install turbo first
RUN [ \
    "npm", \
    "install", \
    "-g", \
    "turbo@^1.12.5" \
    ]

COPY ../ .

# Add missing dependency to landing-app
RUN cd apps/landing-app && pnpm add @radix-ui/react-slot@^1.0.2

RUN [ \
    "pnpm", \
    "turbo", \
    "prune", \
    "web" \
    ]

RUN cd out

ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_APP_DOMAIN
ARG NEXT_PUBLIC_APP_SHORT_DOMAIN

RUN [ \
    "pnpm", \
    "i" \
    ]

RUN [ \
    "pnpm", \
    "build" \
    ]

CMD [ \
    "sh", \
    "-c", \
    "cd apps/web && pnpm start" \
    ]

EXPOSE 8888
