FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY ../apps/redirect-server/go.mod ../apps/redirect-server/go.sum ./

RUN go mod download

COPY ../apps/redirect-server .

RUN go build -o /api ./cmd/api

FROM alpine:latest

COPY --from=builder /api /api

EXPOSE 3002

CMD [ \
    "/api" \
    ]
