root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

# Configuration for `api` main application
[build.api]
  bin = "./tmp/api"
  cmd = "go build -o ./tmp/api ./cmd/api"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_dir = ["cmd/api"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors-api.log"
  post_cmd = ["chmod +x ./tmp/api"]

[run.api]
  cmd = "./tmp/api"
  watch = ["cmd/api"]

# Configuration for `redirectd` main application
[build.redirectd]
  bin = "./tmp/redirectd"
  cmd = "go build -o ./tmp/redirectd ./cmd/redirect"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_dir = ["cmd/redirectd"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors-redirectd.log"
  post_cmd = ["chmod +x ./tmp/redirectd"]

[run.redirectd]
  cmd = "./tmp/redirectd"
  watch = ["cmd/redirectd"]

# Shared configurations
[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
