root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  full_bin = """
  ELASTIC_URL=http://localhost:9200 KAFKA_ADDR=localhost:9092 FAILED_SAVES_LOG_PATH=./aggregator-failed-saves.log ./tmp/analytics-aggregator & 
  ELSATIC_URL=http://localhost:9200 ./tmp/api & 
  ELASTIC_URL=http://localhost:9200 NEXTJS_BASE_URL=http://localhost:8888 LOG_FILE_PATH=./logs/redirectd.log ./tmp/redirectd
  """
  cmd = "go build -o ./tmp/ ./cmd/..."
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  send_interrupt = true
  delay = 500
  kill_delay = 500
  rerun_delay = 500

[run]
  cmd = "./tmp/main"
  watch = ["cmd/redirectd"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
