root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o tmp/main ./cmd/api"
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  post_cmd = ["chmod +x tmp/main"]

[run]
  cmd = "./tmp/main"
  watch = ["cmd/redirectd"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
