apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogov-docs-app
spec:
  template:
    spec:
      containers:
        - name: gogov-docs-app
          env:
            - name: STAGING_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landing-secret
                  key: STAGING_AUTH_PASSWORD
