apiVersion: "kafka.strimzi.io/v1alpha1"
kind: KafkaConnector
metadata:
  name: kafka-connector
  namespace: gogov
  labels:
    strimzi.io/cluster: kafka-connector-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.url: "${DIRECT_URL}"
    plugin.name: "pgoutput"  # Use the logical decoding plugin for PostgreSQL
    database.history.kafka.bootstrap.servers: "kafka-cluster-kafka-brokers:9092"
    database.history.kafka.topic: "schema-changes.inventory"
    include.schema.changes: "true"
    # database.url: "${DIRECT_URL}"
    # database.url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/your_database
    # database.user: ${POSTGRES_USER}
    # database.password: ${POSTGRES_PASSWORD}
    connector.class: "io.debezium.connector.postgresql.PostgresConnector"
    database.hostname: "ps-postgres"
    database.port: "5432"
    # "database.user": "'"$POSTGRES_USER"'",
    # "database.password": "'"$POSTGRES_PASSWORD"'",
    # "database.dbname": "'"$POSTGRES_DB"'",
    database.server.name: "ps-postgres"
    table.include.list: "public.WebhookOutbox"
    topic.prefix: "ps-postgres"
  env:
    - name: DIRECT_URL
      valueFrom:
        secretKeyRef:
          name: web-secret
          key: DIRECT_URL

