apiVersion: "kafka.strimzi.io/v1alpha1"
kind: KafkaConnector
metadata:
  name: kafka-connector
  namespace: gogov
  labels:
    strimzi.io/cluster: kafka-connector-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.url: "${DATABASE_URL}"
    database.server.name: ""
    plugin.name: "pgoutput"  # Use the logical decoding plugin for PostgreSQL
    database.history.kafka.bootstrap.servers: "gogov-kafka:9092"
    database.history.kafka.topic: "schema-changes.inventory"
    include.schema.changes: "true"
  env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: web-secret
        key: DATABASE_URL
