apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaeger-placeholder
          ports:
            - containerPort: 16686   # Jaeger UI port
            - containerPort: 14268   # Jaeger Collector HTTP port
            - containerPort: 14250   # Jaeger gRPC port
            - containerPort: 9411    # Zipkin HTTP port
            - containerPort: 6831    # Jaeger Agent (Thrift Compact protocol) - UDP
              protocol: UDP
            - containerPort: 6832    # Jaeger Agent (Thrift Binary protocol) - UDP
              protocol: UDP
            - containerPort: 5775    # Jaeger Agent (Custom protocol) - UDP
              protocol: UDP
            - containerPort: 5778    # Jaeger Agent (Admin) - TCP
            - containerPort: 4317    # Collector accept OpenTelemetry Protocol (OTLP) over gRPC
            - containerPort: 4318    # Collector accept OpenTelemetry Protocol (OTLP) over HTTP
            - containerPort: 14269   # health check at /
            env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"

