---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
    - protocol: TCP
      port: 4318
      targetPort: 4318
    - protocol: TCP
      port: 4317
      targetPort: 4317

