---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: jaeger-ui 
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: otlp-http 
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317

