apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: kafka-exporter-placeholder
          ports:
            - containerPort: 9308
          env:
            - name: KAFKA_SERVER
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: KAFKA_BROKER_URL
          args:
            - '--kafka.server=$(KAFKA_SERVER)'
