apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-elasticsearch
  namespace: gogov
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: 'true'
reclaimPolicy: Retain
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone
        values:
          - ap-southeast-1a
          - ap-southeast-1b
