apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  namespace: gogov
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-elasticsearch
  resources:
    requests:
      storage: 1Gi
