apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-aggregator
spec:
  template:
    spec:
      containers:
        - name: analytics-aggregator
          env:
            - name: KAFKA_ADDR
              value: b-2.gogovdev.eshbn0.c5.kafka.ap-southeast-1.amazonaws.com:9092
