apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-aggregator
spec:
  template:
    spec:
      containers:
        - name: analytics-aggregator
          env:
            - name: KAFKA_ADDR
              value: b-2.gogovdevtmp.u9vhh4.c5.kafka.ap-southeast-1.amazonaws.com:9092
            - name: ELASTIC_URL
              value: https://gogov-sandbox.es.vpce.ap-southeast-1.aws.elastic-cloud.com
            - name: ELASTIC_USER
              value: elastic
            - name: ELASTIC_PASSWORD
              value: 7lfDfBlctUMNh0ASVsQQ1uc0
