apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-aggregator
spec:
  template:
    spec:
      containers:
        - name: analytics-aggregator
          env:
            - name: KAFKA_ADDR
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: KAFKA_ADDR
            - name: ELASTIC_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: ELASTIC_URL
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: ELASTIC_USER
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: ELASTIC_PASSWORD
