apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirectd
  labels:
    app: redirectd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirectd
  template:
    metadata:
      labels:
        app: redirectd
    spec:
      containers:
        - name: redirectd
          image: redirectd-placeholder
          ports:
            - containerPort: 3000
          env:
            - name: NEXTJS_BASE_URL
              value: "https://app.pautan.org"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/filebeat/logs
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.13.2
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/filebeat/logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config
