apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirectd
  labels:
    app: redirectd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirectd
  template:
    metadata:
      labels:
        app: redirectd
    spec:
      containers:
      - name: redirectd
        image: redirectd-placeholder
        ports:
        - containerPort: 3000
        env:
        - name: NEXTJS_BASE_URL
          value: "https://app.staging.go.gov.my"
