apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster
  labels:
    app: kafka-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      containers:
        - name: kafka
          image: kafka-placeholder
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'zookeeper:2181'
            - name: KAFKA_LISTENERS
              value: 'PLAINTEXT://:9092'
