---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: gogov-kafka-connect
  annotations:
    strimzi.io/use-connector-resources: 'true'
spec:
  version: 3.8.0
  replicas: 3
  bootstrapServers: gogov-kafka-cluster-kafka-bootstrap:9092
  config:
    group.id: gogov-connect-cluster
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-status
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
  resources:
    requests:
      memory: 512Mi
      cpu: '250m'
    limits:
      memory: 1Gi
      cpu: '500m'
