FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /analytics-aggregator ./cmd/analytics-aggregator

FROM alpine:latest

COPY --from=builder /analytics-aggregator /analytics-aggregator

CMD ["/analytics-aggregator"]
