FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /api ./cmd/api

FROM alpine:latest

COPY --from=builder /api /api

# Expose port 3000 to public
EXPOSE 3000

CMD ["/api"]
