FROM quay.io/strimzi/kafka:latest-kafka-3.9.0
USER root

# Install PostgreSQL JDBC driver
RUN curl -L https://jdbc.postgresql.org/download/postgresql-42.6.0.jar -o /opt/kafka/libs/postgresql-42.6.0.jar

# Install Debezium PostgreSQL connector
RUN curl -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.4.0.Final/debezium-connector-postgres-2.4.0.Final-plugin.zip -o /tmp/debezium-connector-postgres.zip \
    && unzip /tmp/debezium-connector-postgres.zip -d /opt/kafka/plugins/ \
    && rm /tmp/debezium-connector-postgres.zip

USER 1001 