apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogov-landing-app-prod
spec:
  template:
    spec:
      containers:
        - name: gogov-landing-app
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: landing-secret-prod
                  key: AUTH_TOKEN
            - name: LANDING_STATS_JSON_URL
              valueFrom:
                secretKeyRef:
                  name: landing-secret-prod
                  key: LANDING_STATS_JSON_URL
