apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogov-docs-app
  labels:
    app: gogov-docs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogov-docs-app
  template:
    metadata:
      labels:
        app: gogov-docs-app
    spec:
      containers:
        - name: gogov-docs-app
          image: gogov-docs-app-placeholder
          ports:
            - containerPort: 3334
          readinessProbe:
            tcpSocket:
              port: 3334
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: port-forward
          image: alpine/socat
          args:
            - tcp-listen:3334,fork,reuseaddr
            - tcp:localhost:3334
          ports:
            - containerPort: 3334
