apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogov-docs-app
  labels:
    app: gogov-docs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogov-docs-app
  template:
    metadata:
      labels:
        app: gogov-docs-app
    spec:
      containers:
        - name: gogov-docs-app
          image: gogov-docs-app-placeholder
          ports:
            - containerPort: 3334
