apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-outbox
  labels:
    app: web-outbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-outbox
  template:
    metadata:
      labels:
        app: web-outbox
    spec:
      containers:
        - name: web-outbox
          image: web-outbox-placeholder
