apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
spec:
  template:
    spec:
      containers:
        - name: cron
          env:
            - name: WEB_BASE
              valueFrom:
                secretKeyRef:
                  name: cron-secrets
                  key: WEB_BASE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: cron-secrets
                  key: API_KEY