apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-api
spec:
  template:
    spec:
      containers:
        - name: redirect-api
          env:
            - name: ELASTIC_URL
              value: https://gogov-sandbox.es.vpce.ap-southeast-1.aws.elastic-cloud.com
            - name: ELASTIC_USER
              value: elastic
            - name: ELASTIC_PASSWORD
              value: 7lfDfBlctUMNh0ASVsQQ1uc0
