apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-api
spec:
  template:
    spec:
      containers:
        - name: redirect-api
          env:
            - name: ELASTIC_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: ELASTIC_URL
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: ELASTIC_USER
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: ELASTIC_PASSWORD
