apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-api
spec:
  template:
    spec:
      containers:
        - name: redirect-api
          env:
            - name: ELASTIC_URL
              value: http://elasticsearch:9200
            - name: ELASTIC_USER
              value: elastic
            - name: ELASTIC_PASSWORD
              value: elastic
