---
apiVersion: v1
kind: Service
metadata:
  name: redirectd
spec:
  selector:
    app: redirect-api
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: redirect-api
spec:
  serviceRef:
    name: redirect-api
    port: 3002
  targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-1:767397910274:targetgroup/gogov-redirect-api/c70bfd99180e72a4
