apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  template:
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka.staging.internal:9092'
