apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "* 3 * * *"  # runs at 3 am every morning
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-container
            image: gogov-cron
            imagePullPolicy: IfNotPresent
            args:
              - "node"
              - "cron.ts"
            env:
            - name: WEB_BASE
              value: http://host.docker.internal:8888 
            ports:
            - containerPort: 5001
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1    