apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron
              image: cron-placeholder
              imagePullPolicy: IfNotPresent
              args:
                - node
                - cron.js
              env:
                - name: WEB_BASE
                  valueFrom:
                    secretKeyRef:
                      name: cron-secret
                      key: WEB_BASE
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: cron-secret
                      key: API_KEY
              ports:
                - containerPort: 5001
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
