apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirectd
spec:
  template:
    spec:
      containers:
        - name: redirectd
          env:
            - name: ELASTIC_URL
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: ELASTIC_URL
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: ELASTIC_USER
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-aggregator-secrets
                  key: ELASTIC_PASSWORD
            - name: TELEMETRY_URL
              valueFrom:
                secretKeyRef:
                  name: redirectd-secrets
                  key: TELEMETRY_URL
            - name: NEXTJS_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: redirectd-secrets
                  key: NEXTJS_BASE_URL
            - name: LOG_FILE_PATH
              valueFrom:
                secretKeyRef:
                  name: redirectd-secrets
                  key: LOG_FILE_PATH
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/filebeat/logs
        - name: filebeat
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/filebeat/logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
          env:
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: redirectd-secrets
                  key: KAFKA_HOST
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config