apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirectd
spec:
  template:
    spec:
      containers:
        - name: redirectd
          env:
            - name: ELASTIC_URL
              valueFrom:
                secretKeyRef:
                  name: anal-secret
                  key: ELASTIC_URL
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: anal-secret
                  key: ELASTIC_USER
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: anal-secret
                  key: ELASTIC_PASSWORD
            - name: TELEMETRY_URL
              value: jaeger:4318
            - name: NEXTJS_BASE_URL
              value: "https://app.pautan.org"
            - name: LOG_FILE_PATH
              value: "/usr/share/filebeat/logs/redirectd.log"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/filebeat/logs
        - name: filebeat
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/filebeat/logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
          env:
            - name: KAFKA_HOST
              value: "b-2.gogovdevtmp.u9vhh4.c5.kafka.ap-southeast-1.amazonaws.com:9092"
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config
