apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirectd
spec:
  template:
    spec:
      containers:
        - name: redirectd
          env:
            - name: ELASTIC_URL
              value: https://gogov-sandbox.es.vpce.ap-southeast-1.aws.elastic-cloud.com
            - name: ELASTIC_USER
              value: elastic
            - name: ELASTIC_PASSWORD
              value: 7lfDfBlctUMNh0ASVsQQ1uc0
            - name: TELEMETRY_URL
              value: localhost:4318
            - name: NEXTJS_BASE_URL
              value: "https://app.pautan.org"
            - name: LOG_FILE_PATH
              value: "/usr/share/filebeat/logs/redirectd.log"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/filebeat/logs
        - name: filebeat
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/filebeat/logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
          env:
            - name: KAFKA_HOST
              value: "b-2.gogovdevtmp.u9vhh4.c5.kafka.ap-southeast-1.amazonaws.com:9092"
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config
