output.kafka:
  hosts: ['${KAFKA_HOST}']
  topic: 'redirect_logs'
  partition.hash:
    hash: ['linkId']
    reachable_only: false
    random: false

filebeat:
  inputs:
    - type: filestream
      id: redirect-server-filestream
      paths:
        - /usr/share/filebeat/logs/*
      parsers:
        - ndjson:
            keys_under_root: true
            add_error_key: true