apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - service.yaml
images:
  - name: redirectd-placeholder
    newName: 767397910274.dkr.ecr.ap-southeast-1.amazonaws.com/gogov-redirectd
patches:
  - path: deployment-patch.yaml
configMapGenerator:
  - name: filebeat-config
    files:
      - filebeat.yml
