---
apiVersion: v1
kind: Service
metadata:
  name: redirectd
spec:
  selector:
    app: redirectd
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: redirectd
spec:
  serviceRef:
    name: redirectd
    port: 3000
  targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-1:767397910274:targetgroup/gogov-redirectd/ad6b13ea9e83938f
