apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: gogov-kafka-connect
  namespace: gogov
  annotations:
    # use-connector-resources configures this KafkaConnect
    # to use KafkaConnector resources to avoid
    # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
# spec:
#   image: 767397910274.dkr.ecr.ap-southeast-1.amazonaws.com/gogov-kafka-connect
#   replicas: 1
#   bootstrapServers: kafka-cluster-kafka-brokers:9092
#   # tls:
#   #   trustedCertificates:
#   #     - secretName: gogov-kafka-connect-ca-cert  # need to change this later by finding a secret created by strimzi
#   #       certificate: ca.crt
#   config:
#     config.storage.replication.factor: 1
#     offset.storage.replication.factor: 1
#     status.storage.replication.factor: 1
#     config.providers: file
#     config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
#     database.url: "${DATABASE_URL}"
#   template:
#     pod:
#       env:
#         - name: DATABASE_URL
#           valueFrom:
#             secretKeyRef:
#               name: web-secret
#               key: DATABASE_URL
spec:
  version: 3.9.0
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-brokers:9092
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    # internal.key.converter  -- deprecated
    # internal.value.converter -- deprecated
    # connect.key.converter.schema.registry.url: http://schema-registry:8081
    # connect.value.converter.schema.registry.url: http://schema-registry:8081
    connect.bootstrap.servers: kafka-cluster-kafka-brokers:9092
    connect.rest.advertised.host.name: debezium
    connect.group.id: 1
    connect.rest.port: 8083
    connect.config.storage.replication.factor: 1
    connect.offset.storage.replication.factor: 1
    connect.status.storage.replication.factor: 1
  image: 767397910274.dkr.ecr.ap-southeast-1.amazonaws.com/gogov-kafka-connect:latest
  # plugins:
  #   - name: debezium-plugins
  #     artifacts:
  #       - type: jar
  #         url: file:///Users/peenixfurface/Documents/GitHub/go-gov-my/docker/debezium-connector-postgres/debezium-core-3.0.5.Final.jar
  
