apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: gogov-kafka-connect
  namespace: gogov
  annotations:
    strimzi.io/use-connector-resources: 'true'
spec:
  image: 767397910274.dkr.ecr.ap-southeast-1.amazonaws.com/gogov-kafka-connect
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap.gogov.svc.cluster.local:9093
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-cluster-ca-cert
        certificate: ca.crt
  resources:
    requests:
      memory: '1Gi'
      cpu: '500m'
    limits:
      memory: '2Gi'
      cpu: '1000m'
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    java.opts: '-Xms512m -Xmx1g -Djava.security.properties=/opt/kafka/config/security.properties'
  externalConfiguration:
    volumes:
      - name: connector-config
        secret:
          secretName: postgres-credentials
