apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: gogov-kafka-connect
  namespace: gogov
  annotations:
    # use-connector-resources configures this KafkaConnect
    # to use KafkaConnector resources to avoid
    # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: 'true'
spec:
  image: 767397910274.dkr.ecr.ap-southeast-1.amazonaws.com/gogov-kafka-connect:sha-befcaea
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap.gogov.svc.cluster.local:9093
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  externalConfiguration:
    volumes:
      - name: connector-config
        secret:
          secretName: postgres-credentials
