apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  namespace: gogov
  annotations:
    strimzi.io/use-connector-resources: 'true'
spec:
  version: 3.9.0
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  template:
    pod:
      containers:
        - name: connect
          env:
            - name: DATABASE_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_HOSTNAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DATABASE_NAME
  build:
    output:
      type: docker
      image: 767397910274.dkr.ecr.ap-southeast-1.amazonaws.com/gogov-kafka-connect:latest
    plugins:
      - name: debezium-postgres
        artifacts:
          - type: zip
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.4.0.Final/debezium-connector-postgres-2.4.0.Final-plugin.zip
