apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: gogov-kafka-connector
  namespace: gogov
  labels:
    strimzi.io/cluster: gogov-kafka-connector
spec:
  template:
    pod:
      env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: DATABASE_NAME
        - name: DIRECT_URL
          valueFrom:
            secretKeyRef:
              name: web-secret
              key: DIRECT_URL
  config:
    plugin.name: pgoutput
    database.hostname: ps-postgres
    database.port: 5432
    database.user: "${DATABASE_USER}"
    database.password: "${POSTGRES_PASSWORD}"
    database.dbname: "${DATABASE_NAME}"
    database.server.name: ps-postgres
    table.include.list: public.WebhookOutbox
    topic.prefix: ps-postgres
    database.url: "${DIRECT_URL}" 