apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-api
  labels:
    app: redirect-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirect-api
  template:
    metadata:
      labels:
        app: redirect-api
    spec:
      containers:
        - name: redirect-api
          image: redirect-api-placeholder
          ports:
            - containerPort: 3002
          env:
            - name: ELASTIC_URL
              value: elastic-url-placeholder
            - name: ELASTIC_USER
              value: elastic-user-placeholder
            - name: ELASTIC_PASSWORD
              value: elastic-password-placeholder
