apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduler-services
spec:
  schedule: '0 3 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduler-services
              image: scheduler-services-placeholder
              imagePullPolicy: IfNotPresent
              env:
                - name: WEB_BASE
                  valueFrom:
                    secretKeyRef:
                      name: scheduler-services-secret
                      key: WEB_BASE
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: scheduler-services-secret
                      key: API_KEY
                - name: DISCORD_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: scheduler-services-secret
                      key: DISCORD_WEBHOOK_URL
                - name: DISCORD_THREAD_ID
                  valueFrom:
                    secretKeyRef:
                      name: scheduler-services-secret
                      key: DISCORD_THREAD_ID
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
