---
apiVersion: v1
kind: Service
metadata:
  name: landing-page
spec:
  selector:
    app: landing-page
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# apiVersion: elbv2.k8s.aws/v1beta1
# kind: TargetGroupBinding
# metadata:
#   name: landing-page
# spec:
#   serviceRef:
#     name: landing-page
#     port: 8080
#   targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-1:767397910274:targetgroup/gogov-dashboard/7b4ca5c7d182b720
