name: Deploy Kafka Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - '.kube/kafka-cluster/**'
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name your-cluster-name --region ${{ env.AWS_REGION }}

      - name: Install Strimzi Operator
        run: |
          kubectl create namespace kafka || true
          kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka

      - name: Deploy Kafka Resources
        run: |
          kubectl apply -f .kube/kafka-cluster/base/kafka.yaml -n kafka
          kubectl apply -f .kube/kafka-cluster/base/kafka-connect.yaml -n kafka
