name: Deploy gogov-kafka-connect
env:
  IMAGE: gogov-kafka-connect
on:
  push:
    branches:
      - main
      - staging
    paths:
      - '.kube/kafka-connect/**'
      - '.kube/debezium-connector/**'
      - '.github/workflows/kafka-connect.yaml'
      - 'docker/**'
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::767397910274:role/github-oidc-provider-aws
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=sha-
      - name: Determine environment
        id: determine-env
        run: |
          if [[ ${{ github.ref }} == refs/heads/staging ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == refs/heads/main ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=development" >> $GITHUB_OUTPUT
          fi
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.kafka-connect
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy with Spinnaker
        run: |
          # Get the first tag (main version tag)
          MAIN_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)

          curl --request POST \
              --url https://spin-gate.govtechmy.dev/webhooks/webhook/github \
              --header 'Content-Type: application/json' \
              --data '{
                "secret": "${{ secrets.SPINNAKER_SECRET }}",
                "artifacts": [
                  {
                    "type": "docker/image",
                    "reference": "'"${MAIN_TAG}"'",
                    "name": "${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE }}",
                    "version": "${{ steps.meta.outputs.version }}"
                  }
                ],
                "environment": "${{ steps.determine-env.outputs.ENVIRONMENT }}"
              }'
