name: Deploy to staging
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::767397910274:role/github-oidc-provider-aws
          aws-region: ap-southeast-1
