name: Deploy gogov-prometheus
env:
  IMAGE: gogov-prometheus
on:
  push:
    tags:
      - 'prometheus@STAGING-v*'
      - 'prometheus@v*'
    paths-ignore:
      - apps/redirect-server/**
      - apps/redirect-pages/**
      - apps/docs-app/**
      - apps/landing-app/**
      - apps/web/**
      - packages/**
      - apps/scheduler-services
      - docker/Dockerfile.web
      - docker/Dockerfile.api
      - docker/Dockerfile.redirectd
      - docker/Dockerfile.outbox
      - docker/Dockerfile.analytics-aggregator
      - docker/Dockerfile.scheduler-services
      - docker/Dockerfile.docs-app
      - docker/Dockerfile.landing-app
  workflow_dispatch:
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::767397910274:role/github-oidc-provider-aws
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE }}
          tags: |
            type=sha
      - name: Determine environment
        id: determine-env
        run: |
          if [[ ${{ github.ref }} == refs/tags/prometheus@STAGING-v* ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == refs/tags/prometheus@v* ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=development" >> $GITHUB_OUTPUT
          fi
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.prometheus
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Log out of Amazon ECR
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
      - name: Deploy with Spinnaker
        run: |
          curl --request POST \
              --url https://spin-gate.govtechmy.dev/webhooks/webhook/github \
              --header 'Content-Type: application/json' \
              --data '{
                "secret": "${{ secrets.SPINNAKER_SECRET }}",
                "artifacts": [
                  {
                    "type": "docker/image",
                    "reference": "${{ steps.meta.outputs.tags }}",
                    "name": "${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE }}",
                    "version": "${{ steps.meta.outputs.version }}"
                  }
                ],
                "environment": "${{ steps.determine-env.outputs.ENVIRONMENT }}"
              }'
