apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: zookeeper
          image: quay.io/strimzi/kafka:0.44.0-kafka-3.8.0
          env:
            - name: LOG_DIR
              value: "/tmp/logs"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ENVIRONMENT
              value: "staging"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 2181
              name: zookeeper-client
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - bin/zkCli.sh -server localhost:2181 ls /
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - bin/zkCli.sh -server localhost:2181 ls /
            initialDelaySeconds: 30
            periodSeconds: 30
